update=2017-10-01 7:53:07 AM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=design 2-rescue
LibName2=power
LibName3=device
LibName4=switches
LibName5=relays
LibName6=motors
LibName7=transistors
LibName8=conn
LibName9=linear
LibName10=regul
LibName11=74xx
LibName12=cmos4000
LibName13=adc-dac
LibName14=memory
LibName15=xilinx
LibName16=microcontrollers
LibName17=dsp
LibName18=microchip
LibName19=analog_switches
LibName20=motorola
LibName21=texas
LibName22=intel
LibName23=audio
LibName24=interface
LibName25=digital-audio
LibName26=philips
LibName27=display
LibName28=cypress
LibName29=siliconi
LibName30=opto
LibName31=atmel
LibName32=contrib
LibName33=valves
LibName34=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName35=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName36=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName37=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName38=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName39=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName40=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName41=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName42=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName43=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName44=C:/Program Files/KiCad/share/kicad/library/74xx
LibName45=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName46=C:/Program Files/KiCad/share/kicad/library/actel
LibName47=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName48=C:/Program Files/KiCad/share/kicad/library/allegro
LibName49=C:/Program Files/KiCad/share/kicad/library/Altera
LibName50=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName51=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName52=C:/Program Files/KiCad/share/kicad/library/atmel
LibName53=C:/Program Files/KiCad/share/kicad/library/audio
LibName54=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName55=C:/Program Files/KiCad/share/kicad/library/bbd
LibName56=C:/Program Files/KiCad/share/kicad/library/bosch
LibName57=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName58=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName59=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName60=C:/Program Files/KiCad/share/kicad/library/conn
LibName61=C:/Program Files/KiCad/share/kicad/library/contrib
LibName62=C:/Program Files/KiCad/share/kicad/library/cypress
LibName63=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName64=C:/Program Files/KiCad/share/kicad/library/device
LibName65=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName66=C:/Program Files/KiCad/share/kicad/library/diode
LibName67=C:/Program Files/KiCad/share/kicad/library/display
LibName68=C:/Program Files/KiCad/share/kicad/library/dsp
LibName69=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName70=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName71=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName72=C:/Program Files/KiCad/share/kicad/library/gennum
LibName73=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName74=C:/Program Files/KiCad/share/kicad/library/hc11
LibName75=C:/Program Files/KiCad/share/kicad/library/infineon
LibName76=C:/Program Files/KiCad/share/kicad/library/intel
LibName77=C:/Program Files/KiCad/share/kicad/library/interface
LibName78=C:/Program Files/KiCad/share/kicad/library/intersil
LibName79=C:/Program Files/KiCad/share/kicad/library/ir
LibName80=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName81=C:/Program Files/KiCad/share/kicad/library/leds
LibName82=C:/Program Files/KiCad/share/kicad/library/LEM
LibName83=C:/Program Files/KiCad/share/kicad/library/linear
LibName84=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName85=C:/Program Files/KiCad/share/kicad/library/maxim
LibName86=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName87=C:/Program Files/KiCad/share/kicad/library/memory
LibName88=C:/Program Files/KiCad/share/kicad/library/microchip
LibName89=C:/Program Files/KiCad/share/kicad/library/modules
LibName90=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName91=C:/Program Files/KiCad/share/kicad/library/motorola
LibName92=C:/Program Files/KiCad/share/kicad/library/motors
LibName93=C:/Program Files/KiCad/share/kicad/library/msp430
LibName94=C:/Program Files/KiCad/share/kicad/library/nxp
LibName95=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName96=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName97=C:/Program Files/KiCad/share/kicad/library/opto
LibName98=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName99=C:/Program Files/KiCad/share/kicad/library/philips
LibName100=C:/Program Files/KiCad/share/kicad/library/power
LibName101=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName102=C:/Program Files/KiCad/share/kicad/library/powerint
LibName103=C:/Program Files/KiCad/share/kicad/library/pspice
LibName104=C:/Program Files/KiCad/share/kicad/library/references
LibName105=C:/Program Files/KiCad/share/kicad/library/regul
LibName106=C:/Program Files/KiCad/share/kicad/library/relays
LibName107=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName108=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName109=C:/Program Files/KiCad/share/kicad/library/sensors
LibName110=C:/Program Files/KiCad/share/kicad/library/silabs
LibName111=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName112=C:/Program Files/KiCad/share/kicad/library/stm8
LibName113=C:/Program Files/KiCad/share/kicad/library/stm32
LibName114=C:/Program Files/KiCad/share/kicad/library/supertex
LibName115=C:/Program Files/KiCad/share/kicad/library/switches
LibName116=C:/Program Files/KiCad/share/kicad/library/texas
LibName117=C:/Program Files/KiCad/share/kicad/library/transf
LibName118=C:/Program Files/KiCad/share/kicad/library/transistors
LibName119=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName120=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName121=C:/Program Files/KiCad/share/kicad/library/valves
LibName122=C:/Program Files/KiCad/share/kicad/library/video
LibName123=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName124=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName125=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName126=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName127=C:/Program Files/KiCad/share/kicad/library/zetex
LibName128=C:/Program Files/KiCad/share/kicad/library/Zilog
